### ISSUE TITLE
Missing class on Laravel 5.3

### ISSUE THREAD

**Issue by imyque** [unicodeveloper/laravel-jusibe#3]
FatalErrorException in JusibeServiceProvider.php line 46:
Class 'Unicodeveloper\Jusibe\Jusibe' not found
in JusibeServiceProvider.php line 46

**Comment by unicodeveloper** [comment]
Did you install the Jusibe PHP library first https://github.com/unicodeveloper/jusibe-php-lib ?

**Comment by imyque** [comment]
Thanks. Please add that information to the installation instruction

**Comment by unicodeveloper** [comment]
But, it has been in the readme right from the time I created the project. Take another look at it 
![add-to-readme](https://cloud.githubusercontent.com/assets/2946769/24033501/749ac180-0aed-11e7-990a-74643e6e3f69.png)
