### ISSUE TITLE
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR) Class 'Unicodeveloper\Jusibe\Jusibe' not found

### ISSUE THREAD

**Issue by osinakayah** [unicodeveloper/laravel-jusibe#4]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Unicodeveloper\Jusibe\Jusibe' not found

**Comment by unicodeveloper** [comment]
After installing the package, did you publish the config file? Also, what Laravel version are you using @osinakayah ?

**Comment by unicodeveloper** [comment]
Did you install the Jusibe PHP library first https://github.com/unicodeveloper/jusibe-php-lib ?

**Comment by osinakayah** [comment]
Yeah, 
I published the config
@unicodeveloper

**Comment by osinakayah** [comment]
No, i didnt add the php library. let me do that now

**Comment by osinakayah** [comment]
I am using laravel 5.5
@unicodeveloper

**Comment by unicodeveloper** [comment]
Please let me know how it works after you have installed the Jusibe PHP library.

I'll have to update this library to ensure that you don't need to install the Jusibe PHP library as an extra step at some point next month.

**Comment by osinakayah** [comment]
@unicodeveloper , it is working now

**Comment by unicodeveloper** [comment]
I'm glad you finally got it to work @osinakayah 😄
